name: Publish to BCR

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: bazel-contrib/publish-to-bcr@v0.2.0
        with:
          # The name of the module as it appears in MODULE.bazel
          moduleName: fire
          # GitHub token for creating the PR
          token: ${{ secrets.GITHUB_TOKEN }}
